#include <syslog.h>

void test( )
{
    //"MyMsgMARK" will appear at the beginning of a message
    //LOG_CONS and LOG_PID are some control arguments
    //LOG_LOCAL1 represent the log file defined by user,not the system
    openlog( "MyMsgMARK", LOG_CONS | LOG_PID, LOG_LOCAL1 ); 
    syslog( LOG_ERR, "This is a syslog test error message generated by program \n" ); 
    syslog( LOG_NOTICE, "This is a syslog test notice message generated by program \n" ); 
    syslog( LOG_DEBUG, "This is a syslog test debug message generated by program \n" );
    closelog(); 
}

void test1( )
{
    //3 << 3 == 24,there are 23 kinds of log including system and user,the msgs of 24 will write into messages file 
    //16~~23 LOCAL0~~LOCAL7 are defined by user
    openlog( 0, 0, ( 3 << 3 ) );
    syslog( LOG_ERR, "This is a syslog test1 error message generated by program\n" );
    syslog( LOG_NOTICE, "This is a syslog test1 notice message generated by program\n" );
    syslog( LOG_DEBUG, "This is a syslog test1 debug message generated by program\n" );
    closelog();
} 
int main(int argc, char **argv) 
{
test(); 
test1();
return 0; 
} 
/**********************************************
syslog configuration file is /etc/syslog.conf
you can define your log type like this:
#Save conflib mesages to conflib.log
local1.*				/var/log/conflib.log
and the default log file is "messages" in the path of "/var/log/messages"
************************************************/
