//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Disign Mode State
//  @ File Name : TCPConnection.cpp
//  @ Date : 2012-3-19
//  @ Author : braveyly
//
//

#include "TCPEstablished.h"
#include "TCPListen.h"
#include "TCPClosed.h"
#include "TCPConnection.h"

TCPConnection::TCPConnection() {
cout<<"TCPConnection::TCPConnection()"<<endl;
	_state = TCPClosed::instance();
}

void TCPConnection::active_open() {
	cout<<"void TCPConnection::active_open()"<<endl;
	if( NULL == _state )
		cout<<"state is null"<<endl;
	_state->active_open(this);
}

void TCPConnection::passive_open() {
	_state->passive_open(this);
}

void TCPConnection::close() {
	_state->close(this);
}

void TCPConnection::acknowlege() {
	_state->acknowlege(this);
}

void TCPConnection::synchronize() {
	_state->synchronize(this);
}

