//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Disign Mode State
//  @ File Name : TCPClosed.h
//  @ Date : 2012-3-19
//  @ Author : braveyly
//
//


#if !defined(_TCPCLOSED_H)
#define _TCPCLOSED_H

#include "TCPState.h"

class TCPClosed : public TCPState {
public:
	static TCPState* instance();
	void active_open(TCPConnection*);
	void passive_open(TCPConnection*);
	void close(TCPConnection*);
	void acknowlege(TCPConnection*);
	void synchronize(TCPConnection*);
private:
	static TCPClosed* _instance;
	TCPClosed(){};
};

#endif  //_TCPCLOSED_H
