//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Disign Mode State
//  @ File Name : TCPConnection.h
//  @ Date : 2012-3-19
//  @ Author : braveyly
//
//


#if !defined(_TCPCONNECTION_H)
#define _TCPCONNECTION_H

class TCPState;
class TCPConnection {
public:
	TCPConnection();
	void active_open();
	void passive_open();
	void close();
	void acknowlege();
	void synchronize();
private:
	friend class TCPState;
	TCPState* _state;
};

#endif  //_TCPCONNECTION_H
