//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Disign Mode State
//  @ File Name : TCPEstablished.cpp
//  @ Date : 2012-3-19
//  @ Author : braveyly
//
//


#include "TCPEstablished.h"
#include "TCPListen.h"
#include "TCPClosed.h"

TCPEstablished* TCPEstablished::_instance = NULL;

TCPState* TCPEstablished::instance() {
	if( _instance )
		return _instance;
	else
		_instance = new TCPEstablished();
}

void TCPEstablished::active_open(TCPConnection* connect) {
	cout<<"do active_open of TCPEstablished"<<endl;
	change_state( connect, TCPListen::instance() );	
}

void TCPEstablished::passive_open(TCPConnection* connect) {
	cout<<"do passive_open of TCPEstablished"<<endl;
	change_state( connect, TCPListen::instance() );	
}

void TCPEstablished::close(TCPConnection* connect) {
	cout<<"do close of TCPEstablished"<<endl;
	change_state( connect, TCPListen::instance() );	
}

void TCPEstablished::acknowlege(TCPConnection* connect) {
	cout<<"do acknowlege of TCPEstablished"<<endl;
	change_state( connect, TCPListen::instance() );	
}

void TCPEstablished::synchronize(TCPConnection* connect) {
	cout<<"do synchronize of TCPEstablished"<<endl;
	change_state( connect, TCPListen::instance() );	
}
