//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Disign Mode State
//  @ File Name : TCPListen.cpp
//  @ Date : 2012-3-19
//  @ Author : braveyly
//
//


#include "TCPEstablished.h"
#include "TCPListen.h"
#include "TCPClosed.h"

TCPListen* TCPListen::_instance = NULL;

TCPState* TCPListen::instance() {
	if( _instance )
		return _instance;
	else
		_instance = new TCPListen();
}

void TCPListen::active_open(TCPConnection* connect) {
	cout<<"do active_open of TCPListen"<<endl;
	change_state( connect, TCPClosed::instance() );		
}

void TCPListen::passive_open(TCPConnection* connect) {
	cout<<"do passive_open of TCPListen"<<endl;
	change_state( connect, TCPClosed::instance() );		
}

void TCPListen::close(TCPConnection* connect) {
	cout<<"do close of TCPListen"<<endl;
	change_state( connect, TCPClosed::instance() );	
}

void TCPListen::acknowlege(TCPConnection* connect) {
	cout<<"do acknowlege of TCPListen"<<endl;
	change_state( connect, TCPClosed::instance() );
}

void TCPListen::synchronize(TCPConnection* connect) {
	cout<<"do synchronize of TCPListen"<<endl;
	change_state( connect, TCPClosed::instance() );
}
