//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Disign Mode State
//  @ File Name : TCPListen.h
//  @ Date : 2012-3-19
//  @ Author : braveyly
//
//


#if !defined(_TCPLISTEN_H)
#define _TCPLISTEN_H

#include "TCPState.h"

class TCPListen : public TCPState {
public:
	static TCPState* instance();
	void active_open(TCPConnection*);
	void passive_open(TCPConnection*);
	void close(TCPConnection*);
	void acknowlege(TCPConnection*);
	void synchronize(TCPConnection*);
private:
	static TCPListen* _instance;
	TCPListen(){};
};

#endif  //_TCPLISTEN_H
