//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Disign Mode State
//  @ File Name : TCPState.h
//  @ Date : 2012-3-19
//  @ Author : braveyly
//
//


#if !defined(_TCPSTATE_H)
#define _TCPSTATE_H
#include <iostream>
#include <string>
using namespace::std;

class TCPConnection;
class TCPState {
public:
	virtual void active_open(TCPConnection*)=0;
	virtual void passive_open(TCPConnection*)=0;
	virtual void close(TCPConnection*)=0;
	virtual void acknowlege(TCPConnection*)=0;
	virtual void synchronize(TCPConnection*)=0;
protected:
	void change_state(TCPConnection*, TCPState*);
};

#endif  //_TCPSTATE_H
