//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Disign Mode Strategy
//  @ File Name : Context.h
//  @ Date : 2012-3-20
//  @ Author : braveyly
//
//


#if !defined(_CONTEXT_H)
#define _CONTEXT_H
#include "Strategy.h"

class Context {
public:
	void context_algorithm_interface();
	void set_strategy(Strategy*);
	Context();
private:
	Strategy* _strategy;
};

#endif  //_CONTEXT_H
