//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Disign Mode Strategy
//  @ File Name : Context.cpp
//  @ Date : 2012-3-20
//  @ Author : braveyly
//
//


#include "Context.h"

void Context::context_algorithm_interface() {
	_strategy->algorithm_interface();
}

void Context::set_strategy(Strategy* stg) {
	_strategy = stg;
}

Context::Context():_strategy(NULL){

}

