//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Disign Mode Strategy
//  @ File Name : StrategyB.cpp
//  @ Date : 2012-3-20
//  @ Author : braveyly
//
//


#include "StrategyB.h"

void StrategyB::algorithm_interface() {
	cout<<"strategy b algorithm interface"<<endl;
}
