//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Disign Mode Strategy
//  @ File Name : StrategyA.h
//  @ Date : 2012-3-20
//  @ Author : braveyly
//
//


#if !defined(_STRATEGYA_H)
#define _STRATEGYA_H

#include "Strategy.h"

class StrategyA : public Strategy {
public:
	void algorithm_interface();
	StrategyA(){};
};

#endif  //_STRATEGYA_H
