//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Disign Mode Strategy
//  @ File Name : StrategyB.h
//  @ Date : 2012-3-20
//  @ Author : braveyly
//
//


#if !defined(_STRATEGYB_H)
#define _STRATEGYB_H

#include "Strategy.h"

class StrategyB : public Strategy {
public:
	void algorithm_interface();
	StrategyB(){};
};

#endif  //_STRATEGYB_H
