//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Disign Mode Strategy
//  @ File Name : StrategyA.cpp
//  @ Date : 2012-3-20
//  @ Author : braveyly
//
//


#include "StrategyA.h"

void StrategyA::algorithm_interface() {
	cout<<"strategy a algorithm interface"<<endl;
}
