//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Disign Mode Strategy
//  @ File Name : Strategy.h
//  @ Date : 2012-3-20
//  @ Author : braveyly
//
//


#if !defined(_STRATEGY_H)
#define _STRATEGY_H
#include <iostream>
using namespace::std;

class Strategy {
public:
	virtual void algorithm_interface()=0;
};

#endif  //_STRATEGY_H
