//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Disign Mode Observe
//  @ File Name : CobObserve.h
//  @ Date : 2012-3-19
//  @ Author : braveyly
//
//


#if !defined(_COBOBSERVE_H)
#define _COBOBSERVE_H
#include "Subject.h"
#include "Observe.h"

class CobObserve : public Observe {
public:
	void operate(int data);
	void show_view();
	CobObserve(){};
};

#endif  //_COBOBSERVE_H
