//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Disign Mode Observe
//  @ File Name : CobObserve.cpp
//  @ Date : 2012-3-19
//  @ Author : braveyly
//
//


#include "CobObserve.h"

void CobObserve::operate(int data) {
	get_subject()->set_data(data);
}

void CobObserve::show_view() {
	cout<<"refresh cob view to"<<get_subject()->get_data()<<endl;
}
