//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Disign Mode Observe
//  @ File Name : ColumnObserve.h
//  @ Date : 2012-3-19
//  @ Author : braveyly
//
//


#if !defined(_COLUMNOBSERVE_H)
#define _COLUMNOBSERVE_H
#include "Subject.h"
#include "Observe.h"

class ColumnObserve : public Observe {
public:
	void operate(int);
	void show_view();
	ColumnObserve(){};
};

#endif  //_COLUMNOBSERVE_H
