//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Disign Mode Observe
//  @ File Name : Observe.h
//  @ Date : 2012-3-19
//  @ Author : braveyly
//
//


#if !defined(_OBSERVE_H)
#define _OBSERVE_H

class Subject;

class Observe {
private:
	Subject* _sub;
public:
	virtual  void operate(int)=0;
	virtual void show_view()=0;
	virtual void set_subject(Subject*);
	virtual Subject* get_subject();
};

#endif  //_OBSERVE_H
