//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Disign Mode Observe
//  @ File Name : Observe.cpp
//  @ Date : 2012-3-19
//  @ Author : braveyly
//
//

#include "Subject.h"
#include "Observe.h"

void Observe::set_subject(Subject* sub) {
	_sub = sub;
	_sub->attach_observe(this);
}

Subject* Observe::get_subject() {
	return _sub;
}

