//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Disign Mode Observe
//  @ File Name : Subject.h
//  @ Date : 2012-3-19
//  @ Author : braveyly
//
//


#if !defined(_SUBJECT_H)
#define _SUBJECT_H
#include <iostream>
#include <list>
using namespace::std;
#include "Observe.h"

class Subject {
public:
	virtual void attach_observe(Observe*);
	virtual void deattach_observe(Observe*);
	virtual void notify();
	virtual int get_data()=0;
	virtual void set_data(int)=0;
private:
	list<Observe*> _observe_list;
};

#endif  //_SUBJECT_H
