//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Disign Mode Observe
//  @ File Name : TableObserve.cpp
//  @ Date : 2012-3-19
//  @ Author : braveyly
//
//


#include "TableObserve.h"

void TableObserve::operate(int data) {
	get_subject()->set_data(data);
}

void TableObserve::show_view() {
	cout<<"refresh table view to"<<get_subject()->get_data()<<endl;
}
