all:composite
composite:equipment.cpp composite_equipment.cpp tire.cpp steer_wheel.cpp basic_vehicle.cpp intelligent_vehicle.cpp engine_motor.cpp navigator.cpp test_composite.cpp
	g++ $? -o $@
clean:
	rm -rf *.o *.orig composite
run:
	./composite
