#****************************************************************************
#
#  Copyright (c) 2008 TECOM Corporation
#  All Rights Reserved
#  No portions of this material may be reproduced in any form without the
#  written permission of:
#          TECOM Corporation
#          #18, Huaguang Road
#          Wuhan, PR China 430074
#  All information contained in this document is TECOM Corporation
#  company private, proprietary, and trade secret.
# #***************************************************************************** 
OBJ=assert.o  eid.o  file.o  hexbinary.o  image.o  memory.o  network.o  strconv.o  timer.o  timestamp.o logging.o util.o
VERSION=1
LIBNAME=liboal
CFLAGS+=-DTCM_LOG3 -fPIC -g -Wall -c
CFLAGS+=-I$(ROOTDIR)/include/liboal

dynamic: liboal 

all: liboal 

.c.o:
	$(CC) $(INCLUDES) $(CFLAGS) $*.c

liboal: $(OBJ)
	${CC} -shared -Wl,-soname,${LIBNAME}.so -o ${LIBNAME}.so.${VERSION} ${OBJ} -lpthread -lc -lcrypt
	ln -sf ${LIBNAME}.so.${VERSION} $(LIBNAME).so 

clean:
	rm -f *.o ${LIBNAME}.so*

romfs:
	if [ -f ${LIBNAME}.so.${VERSION} ] ; then \
		$(ROMFSINST) ${LIBNAME}.so.${VERSION} /lib/${LIBNAME}.so.${VERSION} ; \
		$(ROMFSINST) -s $(LIBNAME).so.$(VERSION) /lib/$(LIBNAME).so ;  \
	fi

