//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Disign Mode Visitor
//  @ File Name : ConcreteVisitor2.h
//  @ Date : 2012-3-20
//  @ Author : braveyly
//
//


#if !defined(_CONCRETEVISITOR2_H)
#define _CONCRETEVISITOR2_H

#include "Visitor.h"

class ConcreteVisitor2 : public Visitor {
public:
	void visit_concrete_element_a(ElementA*);
	void visit_concrete_element_b(ElementB*);
	ConcreteVisitor2(){};
};

#endif  //_CONCRETEVISITOR2_H
