//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Disign Mode Visitor
//  @ File Name : ConcreteVisitor1.h
//  @ Date : 2012-3-20
//  @ Author : braveyly
//
//


#if !defined(_CONCRETEVISITOR1_H)
#define _CONCRETEVISITOR1_H

#include "Visitor.h"

class ConcreteVisitor1 : public Visitor {
public:
	void visit_concrete_element_a(ElementA*);
	void visit_concrete_element_b(ElementB*);
	ConcreteVisitor1(){};
};

#endif  //_CONCRETEVISITOR1_H
