//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Disign Mode Visitor
//  @ File Name : ElementB.cpp
//  @ Date : 2012-3-20
//  @ Author : braveyly
//
//


#include "ElementB.h"
#include "ConcreteVisitor1.h"
#include "ConcreteVisitor2.h"

void ElementB::accept(Visitor* vis) {
	vis->visit_concrete_element_b(this);
}

void ElementB::operation_b() {
	cout<<"operation b of element b"<<endl;
}
