//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Disign Mode Visitor
//  @ File Name : ElementB.h
//  @ Date : 2012-3-20
//  @ Author : braveyly
//
//


#if !defined(_ELEMENTB_H)
#define _ELEMENTB_H

#include "Element.h"

class ElementB : public Element {
public:
	void accept(Visitor*);
	void operation_b();
	ElementB(){};
};

#endif  //_ELEMENTB_H
