//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Disign Mode Visitor
//  @ File Name : Element.h
//  @ Date : 2012-3-20
//  @ Author : braveyly
//
//


#if !defined(_ELEMENT_H)
#define _ELEMENT_H
#include <iostream>
using namespace::std;

class Visitor;

class Element {
public:
	virtual void accept(Visitor*)=0;
};

#endif  //_ELEMENT_H
