//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Disign Mode Visitor
//  @ File Name : ElementA.cpp
//  @ Date : 2012-3-20
//  @ Author : braveyly
//
//


#include "ElementA.h"
#include "ConcreteVisitor1.h"
#include "ConcreteVisitor2.h"

void ElementA::accept(Visitor* vis) {
	vis->visit_concrete_element_a(this);
}

void ElementA::operation_a() {
	cout<<"operation of element a"<<endl;
}
