//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Disign Mode Visitor
//  @ File Name : ElementA.h
//  @ Date : 2012-3-20
//  @ Author : braveyly
//
//


#if !defined(_ELEMENTA_H)
#define _ELEMENTA_H

#include "Element.h"

class ElementA : public Element {
public:
	void accept(Visitor*);
	void operation_a();
	ElementA(){};
};

#endif  //_ELEMENTA_H
