//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Design Mode
//  @ File Name : Application.h
//  @ Date : 2012-3-16
//  @ Author : braveyly
//
//


#if !defined(_APPLICATION_H)
#define _APPLICATION_H

#include "HelpHandler.h"

#include <iostream>
#include <string>
using namespace::std;

class Application : public HelpHandler {
public:
	void print_helper(HelpType);
	Application(HelpType, HelpHandler*);
	~Application(){};
};

#endif  //_APPLICATION_H
