//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Design Mode
//  @ File Name : Button.h
//  @ Date : 2012-3-16
//  @ Author : braveyly
//
//


#if !defined(_BUTTON_H)
#define _BUTTON_H

#include "HelpHandler.h"

class Button : public HelpHandler {
public:
	void print_helper(HelpType);
	Button(HelpType, HelpHandler*);
	~Button();
};

#endif  //_BUTTON_H
