//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Design Mode
//  @ File Name : Button.cpp
//  @ Date : 2012-3-16
//  @ Author : braveyly
//
//


#include "Button.h"

void Button::print_helper(HelpType type) {
	if( get_help_type() == type || NULL == get_help_handler() )
		cout<<"the help info of button"<<endl;
	else
		get_help_handler()->print_helper(type);
}

Button::Button(HelpType type, HelpHandler* handler):HelpHandler(type,handler) {

}

