//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Design Mode
//  @ File Name : Dialog.cpp
//  @ Date : 2012-3-16
//  @ Author : braveyly
//
//


#include "Dialog.h"

void Dialog::print_helper(HelpType type) {
	if( get_help_type() == type || NULL == get_help_handler() )
		cout<<"the help info of dialog"<<endl;
	else
		get_help_handler()->print_helper(type);
}

Dialog::Dialog(HelpType type, HelpHandler* handler):HelpHandler(type, handler) {

}

