//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Design Mode
//  @ File Name : Dialog.h
//  @ Date : 2012-3-16
//  @ Author : braveyly
//
//


#if !defined(_DIALOG_H)
#define _DIALOG_H

#include "HelpHandler.h"

class Dialog : public HelpHandler {
public:
	void print_helper(HelpType);
	Dialog(HelpType, HelpHandler*);
	~Dialog(){};
};

#endif  //_DIALOG_H
