//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Design Mode
//  @ File Name : HelpHandler.h
//  @ Date : 2012-3-16
//  @ Author : braveyly
//
//


#if !defined(_HELPHANDLER_H)
#define _HELPHANDLER_H
#include <iostream>
#include <string>
using namespace::std;

typedef enum _Help_Type{
	TEXT_HELP_TYPE =0,
	BUTTON_HELP_TYPE,
	DIALOG_HELP_TYPE,
	APPLICATION_HELP_TYPE,
	NONE_HELP_TYPE,
}HelpType;

class HelpHandler {
public:
	HelpHandler(HelpType, HelpHandler*);
	~HelpHandler(){};
	virtual void print_helper(HelpType);
	HelpType get_help_type();
	HelpHandler* get_help_handler();
private:
	HelpType _help_type;
	HelpHandler* _successer;
};

#endif  //_HELPHANDLER_H

