//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Design Mode
//  @ File Name : Text.cpp
//  @ Date : 2012-3-16
//  @ Author : braveyly
//
//


#include "Text.h"

void Text::print_helper(HelpType type) {
	if( get_help_type() == type || NULL == get_help_handler() )
		cout<<"the help info of text"<<endl;
	else
		get_help_handler()->print_helper(type);
}
