//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Disign Mode Memento
//  @ File Name : Memento.cpp
//  @ Date : 2012-3-19
//  @ Author : braveyly
//
//


#include "Memento.h"

Memento::Memento() {

}

Memento::Memento(int st):_state(st) {

}

void Memento::set_state(int st) {
	_state = st;
}

int Memento::get_state() {
	return _state;
}

