//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Disign Mode Memento
//  @ File Name : Originator.h
//  @ Date : 2012-3-19
//  @ Author : braveyly
//
//


#if !defined(_ORIGINATOR_H)
#define _ORIGINATOR_H
#include "Memento.h"

class Originator {
public:
	Memento* create_memento();
	void restore_to_memento(Memento*);
	void set_state(int);
	int get_state();
	void print_state();
	Originator(int);
	Originator();
private:
	int _state;
};

#endif  //_ORIGINATOR_H
