//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Disign Mode Memento
//  @ File Name : Originator.cpp
//  @ Date : 2012-3-19
//  @ Author : braveyly
//
//


#include "Originator.h"

Memento* Originator::create_memento() {
	return new Memento(_state);
}

void Originator::restore_to_memento(Memento* mmt) {
	_state = mmt->_state;
}

void Originator::set_state(int st) {
	_state = st;
}

int Originator::get_state() {
	return _state;
}	

void Originator::print_state() {
	cout<<"originator state"<<_state<<endl;
}

Originator::Originator(int st):_state(st) {

}

Originator::Originator() {

}

