//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Design Mode
//  @ File Name : Charactor.h
//  @ Date : 2012-3-15
//  @ Author : 
//
//


#if !defined(_CHARACTOR_H)
#define _CHARACTOR_H

#include "Glyph.h"

class Charactor : public Glyph {
public:
	void draw(FONT*, POSITION*);
	Charactor(char);
	char get_char();
public:
	char _char_content;
};

#endif  //_CHARACTOR_H
