//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Design Mode
//  @ File Name : Charactor.cpp
//  @ Date : 2012-3-15
//  @ Author : 
//
//


#include "Charactor.h"

void Charactor::draw(FONT* ft, POSITION* pn) {
	cout<<"Charactor::draw"<<"_char_content="<<_char_content
		<<"\tsize/color"<<ft->size<<ft->color
		<<"x/y"<<pn->x<<pn->y<<endl;
}

Charactor::Charactor(char chr):Glyph() {
	_char_content = chr;

}

char Charactor::get_char()
{
	return _char_content;
}

