//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Design Mode
//  @ File Name : Glyph.h
//  @ Date : 2012-3-15
//  @ Author : 
//
//


#if !defined(_GLYPH_H)
#define _GLYPH_H
#include "common_def.h"

class Glyph {
public:
	virtual void draw(FONT*, POSITION*){};
	Glyph(){};
	~Glyph(){};
};

#endif  //_GLYPH_H
