//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Design Mode
//  @ File Name : Row.cpp
//  @ Date : 2012-3-15
//  @ Author :
//
//


#include "Row.h"

void Row::draw ( FONT* ft, POSITION* pn )
{
    list<Glyph*>::iterator itr ;

    if ( _list_gph.size() )
        for ( itr = _list_gph.begin();itr != _list_gph.end();itr++ )
        {
            ( *itr )->draw ( ft, pn );
        }
}

int Row::add_glyph ( Glyph* gph )
{
	if( _list_gph.size() > _total )
	{
		cout<<"the list of row is full"<<endl;
		return -1;
	}
	
    _list_gph.push_back ( gph );
	return 0;
}

Row::Row ( int total )
{
    _total = total;
    _list_gph.clear();
}

