//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Disign Mode Template
//  @ File Name : AlgorithmTemplate.cpp
//  @ Date : 2012-3-19
//  @ Author : braveyly
//
//


#include "AlgorithmTemplate.h"

void AlgorithmTemplate::algorithm_operate() {
	this->primitive_method_a();
	this->primitive_method_b();
}
