//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Disign Mode Template
//  @ File Name : AlgorithmTemplate.h
//  @ Date : 2012-3-19
//  @ Author : braveyly
//
//


#if !defined(_ALGORITHMTEMPLATE_H)
#define _ALGORITHMTEMPLATE_H
#include <iostream>
#include <string>
using namespace::std;

class AlgorithmTemplate {
public:
	void algorithm_operate();
protected:
	virtual void primitive_method_a()=0;
	virtual void primitive_method_b()=0;
};

#endif  //_ALGORITHMTEMPLATE_H
