//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Disign Mode Template
//  @ File Name : ComplicatedAlgorithm.h
//  @ Date : 2012-3-19
//  @ Author : braveyly
//
//


#if !defined(_COMPLICATEDALGORITHM_H)
#define _COMPLICATEDALGORITHM_H

#include "AlgorithmTemplate.h"

class ComplicatedAlgorithm : public AlgorithmTemplate {
public:
	ComplicatedAlgorithm(){};
	void primitive_method_a();
	void primitive_method_b();
};

#endif  //_COMPLICATEDALGORITHM_H
