//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Disign Mode Template
//  @ File Name : ComplicatedAlgorithm.cpp
//  @ Date : 2012-3-19
//  @ Author : braveyly
//
//


#include "ComplicatedAlgorithm.h"

void ComplicatedAlgorithm::primitive_method_a() {
	cout<<"complicated algorithm for primitive method a"<<endl;
}

void ComplicatedAlgorithm::primitive_method_b() {
	cout<<"complicated algorithm for primitive method b"<<endl;
}

