//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Disign Mode Template
//  @ File Name : SimpleAlgorithm.h
//  @ Date : 2012-3-19
//  @ Author : braveyly
//
//


#if !defined(_SIMPLEALGORITHM_H)
#define _SIMPLEALGORITHM_H

#include "AlgorithmTemplate.h"

class SimpleAlgorithm : public AlgorithmTemplate {
public:
	SimpleAlgorithm(){};
protected:
	void primitive_method_a();
	void primitive_method_b();
};

#endif  //_SIMPLEALGORITHM_H
