//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Disign Mode Template
//  @ File Name : SimpleAlgorithm.cpp
//  @ Date : 2012-3-19
//  @ Author : braveyly
//
//


#include "SimpleAlgorithm.h"

void SimpleAlgorithm::primitive_method_a() {
	cout<<"simple algorithm for primitive method a"<<endl;
}

void SimpleAlgorithm::primitive_method_b() {
	cout<<"simple algorithm for primitive method b"<<endl;
}

