//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Design Mode
//  @ File Name : DbForum.cpp
//  @ Date : 2012-3-16
//  @ Author : braveyly
//
//


#include "DbForum.h"

int DbForum::set_forum_name(string name) {
_name = name;
cout<<"succeed to set the name of forum to"<<_name<<endl;
}

DbForum::DbForum(int auth):Forum(auth),_name("") {

}

