//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Design Mode
//  @ File Name : DbForum.h
//  @ Date : 2012-3-16
//  @ Author : braveyly
//
//


#if !defined(_DBFORUM_H)
#define _DBFORUM_H

#include <iostream>
#include <string>
using namespace::std;
#include "Forum.h"

class DbForum : public Forum {
public:
	int set_forum_name(string name);
	DbForum(int);
	~DbForum();
private:
	string _name;
};

#endif  //_DBFORUM_H
