//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Design Mode
//  @ File Name : Forum.cpp
//  @ Date : 2012-3-16
//  @ Author : braveyly
//
//


#include "Forum.h"

int Forum::set_forum_name(string name) {

}

int Forum::get_authorization() {
	return authorization;
}

Forum::Forum(int auth):authorization(auth) {

}

