//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Design Mode
//  @ File Name : ForumProxy.h
//  @ Date : 2012-3-16
//  @ Author : braveyly
//
//


#if !defined(_FORUMPROXY_H)
#define _FORUMPROXY_H

#include <iostream>
#include <string>
using namespace::std;
#include "Forum.h"

class ForumProxy : public Forum {
public:
	int set_forum_name(string name);
	int is_system_user(int auth);
	ForumProxy(Forum*);
	~ForumProxy();
private:
	Forum* _forum;
};

#endif  //_FORUMPROXY_H
