//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Design Mode
//  @ File Name : ForumProxy.cpp
//  @ Date : 2012-3-16
//  @ Author : braveyly
//
//


#include "ForumProxy.h"

int ForumProxy::set_forum_name(string name) {
	if(  is_system_user(_forum->get_authorization()) )
		_forum->set_forum_name(name);
	else
		cout<<"Failed to set forum name for not authorization"<<endl;
}

int ForumProxy::is_system_user(int auth) {
	if( auth > 2 )
		return 1;
	else
		return 0;
}

ForumProxy::ForumProxy(Forum* fm):Forum(0),_forum(fm) {

}

