DATA SEGMENT
DATA1 DB 4 dup(0)
DATA2 DB 4 dup(0)
DATA3 DB 5 dup(0)
DATA ENDS
CODE SEGMENT
ASSUME CS:CODE,DS:DATA
START:MOV AX, DATA
      MOV DS, AX      
      MOV DATA1, 91H
      MOV DATA1+1, 12H
      MOV DATA1+2, 13H
      MOV DATA1+3, 84H
      MOV DATA2, 91H
      MOV DATA2+1,22H
      MOV DATA2+2,23H
      MOV DATA2+3,84H
      CALL MADD
      MOV AH,4CH
      INT 21H
MADD PROC
     PUSH AX
     PUSH CX
     PUSH SI
     MOV  CX,2
     XOR  SI, SI
MADD1:MOV AX, WORD PTR DATA1[SI]
      ADC AX, WORD PTR DATA2[SI]
      MOV WORD PTR DATA3[SI], AX
      INC SI
      INC SI
      LOOP MADD1
      XOR AL,AL
      ADC AL,0
      MOV BYTE PTR DATA3+4,AL
      POP SI
      POP CX
      POP AX
      RET
MADD  ENDP

CODE ENDS
     END START
