//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Design Mode Mediator
//  @ File Name : ColleageA.h
//  @ Date : 2012-3-19
//  @ Author : braveyly
//
//


#if !defined(_COLLEAGEA_H)
#define _COLLEAGEA_H

#include "Colleage.h"

class ColleageA : public Colleage {
public:
	ColleageA(Mediator*);
	void action();
};

#endif  //_COLLEAGEA_H
