//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Design Mode Mediator
//  @ File Name : ColleageB.h
//  @ Date : 2012-3-19
//  @ Author : braveyly
//
//


#if !defined(_COLLEAGEB_H)
#define _COLLEAGEB_H

#include "Colleage.h"

class ColleageB : public Colleage {
public:
	ColleageB(Mediator*);
	void action();
};

#endif  //_COLLEAGEB_H
