//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Design Mode Mediator
//  @ File Name : ConcreteMediator.cpp
//  @ Date : 2012-3-19
//  @ Author : braveyly
//
//


#include "ConcreteMediator.h"

int ConcreteMediator::connect_colleage ( Colleage* a, Colleage* b )
{
    _colleage_a = a;
    _colleage_b = b;
}

void ConcreteMediator::set_colleage_a ( Colleage* a )
{
    _colleage_a = a;
}

void ConcreteMediator::set_colleage_b ( Colleage* b )
{
    _colleage_b = b;
}

Colleage* ConcreteMediator::get_colleage_a()
{
    return _colleage_a;
}

Colleage* ConcreteMediator::get_colleage_b()
{
    return _colleage_b;
}

ConcreteMediator::ConcreteMediator () : Mediator()
{

}

void ConcreteMediator::doActionFromAToB()
{
   _colleage_b->set_state( _colleage_a->get_state() );
}

void ConcreteMediator::doActoinFromBToA()
{
	_colleage_a->set_state( _colleage_b->get_state() );
}