//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Design Mode Mediator
//  @ File Name : ConcreteMediator.h
//  @ Date : 2012-3-19
//  @ Author : braveyly
//
//


#if !defined(_CONCRETEMEDIATOR_H)
#define _CONCRETEMEDIATOR_H
#include "Colleage.h"
#include "Mediator.h"

class ConcreteMediator : public Mediator {
public:
	int connect_colleage(Colleage*, Colleage*);
	void set_colleage_a(Colleage*);
	void set_colleage_b(Colleage*);
	Colleage* get_colleage_a();
	Colleage* get_colleage_b();
	ConcreteMediator();
	void doActionFromAToB();
	void doActoinFromBToA();
private:
	Colleage* _colleage_a;
	Colleage* _colleage_b;
};

#endif  //_CONCRETEMEDIATOR_H
