//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Design Mode Mediator
//  @ File Name : Mediator.cpp
//  @ Date : 2012-3-19
//  @ Author : braveyly
//
//


#include "Mediator.h"

Mediator::Mediator() {

}
