//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Disign Mode No-Mediator
//  @ File Name : Colleage.cpp
//  @ Date : 2012-3-19
//  @ Author : braveyly
//
//


#include "Colleage.h"

string Colleage::get_state() {
	return state;
}

void Colleage::set_state(string str) {
	state = str;
}

Colleage* Colleage::get_related_colleage() {
	return _related_colleage;
}

void Colleage::set_colleage(Colleage* clg) {
	_related_colleage =  clg;
}

void Colleage::action() {

}

Colleage::Colleage(Colleage* clg) {
	_related_colleage = clg;
}

Colleage::Colleage() {

}

