//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Disign Mode No-Mediator
//  @ File Name : ColleageA.cpp
//  @ Date : 2012-3-19
//  @ Author : braveyly
//
//


#include "ColleageA.h"

ColleageA::ColleageA(Colleage* clg):Colleage(clg) {

}

ColleageA::ColleageA() {

}

void ColleageA::action() {
	this->set_state(get_related_colleage()->get_state());
	cout<<"a action"<<get_state()<<endl;
}

