//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Disign Mode No-Mediator
//  @ File Name : ColleageB.cpp
//  @ Date : 2012-3-19
//  @ Author : braveyly
//
//


#include "ColleageB.h"

ColleageB::ColleageB(Colleage* clg):Colleage(clg) {

}

ColleageB::ColleageB() {

}

void ColleageB::action() {
	this->set_state(get_related_colleage()->get_state());
	cout<<"b action"<<get_state()<<endl;
}

