//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Disign Mode No-Mediator
//  @ File Name : ColleageB.h
//  @ Date : 2012-3-19
//  @ Author : braveyly
//
//


#if !defined(_COLLEAGEB_H)
#define _COLLEAGEB_H

#include "Colleage.h"

class ColleageB : public Colleage {
public:
	ColleageB(Colleage*);
	ColleageB();
	void action();
};

#endif  //_COLLEAGEB_H
