all:factory
factory:factory.cpp product.cpp concrete_product.cpp concrete_factory.cpp test_factory.cpp
	g++ factory.cpp product.cpp concrete_product.cpp concrete_factory.cpp test_factory.cpp -o factory
run:
	./factory
clean:
	rm -rf *.o *.orig factory
