DATA SEGMENT
DATA ENDS
CODE SEGMENT
ASSUME DS:DATA, CS:CODE
START:MOV AX,DATA
      MOV DS,AX
      MOV AL,'B'
      CALL UPTOLOW
      MOV AH,4CH
      INT 21H
UPTOLOW PROC
      PUSHF
      CMP AL, 'A'
      JB UPTOLOW1
      CMP AL, 'Z'
      JA UPTOLOW1
      ADD AL, 'a'-'A'
UPTOLOW1: POPF
         RET
UPTOLOW ENDP

CODE ENDS
     END START
