//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Design Mode Command
//  @ File Name : Command.cpp
//  @ Date : 2012-3-16
//  @ Author :braveyly
//
//


#include "Command.h"

Command::Command(Receiver* rec):_receiver(rec){

}

void Command::execute() {

}

Receiver* Command::get_receiver()
{
	return _receiver;
}