//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Design Mode Command
//  @ File Name : Command.h
//  @ Date : 2012-3-16
//  @ Author :braveyly
//
//


#if !defined(_COMMAND_H)
#define _COMMAND_H

#include "Receiver.h"

class Command {
public:
	Command(Receiver*);
	virtual void execute();
	Receiver* get_receiver();
private:
	Receiver* _receiver;
};

#endif  //_COMMAND_H
