//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Design Mode Command
//  @ File Name : CopyCommand.cpp
//  @ Date : 2012-3-16
//  @ Author :braveyly
//
//


#include "CopyCommand.h"

CopyCommand::CopyCommand(Receiver* rec):Command(rec) {

}

void CopyCommand::execute()
{
	get_receiver()->copy_action();
}