//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Design Mode Command
//  @ File Name : CopyCommand.h
//  @ Date : 2012-3-16
//  @ Author :braveyly
//
//


#if !defined(_COPYCOMMAND_H)
#define _COPYCOMMAND_H

#include "Command.h"

class CopyCommand : public Command {
public:
	CopyCommand(Receiver*);
	void execute();
};

#endif  //_COPYCOMMAND_H
