//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Design Mode Command
//  @ File Name : Document.cpp
//  @ Date : 2012-3-16
//  @ Author :braveyly
//
//


#include "Document.h"

void Document::copy_action() {
	cout<<"copy action of document"<<endl;
}

void Document::paste_copy() {
	cout<<"paste action of document"<<endl;
}

void Document::open_action() {
	cout<<"open action of document"<<endl;
}

void Document::close_action() {
	cout<<"close action of document"<<endl;
}

