//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Design Mode Command
//  @ File Name : Document.h
//  @ Date : 2012-3-16
//  @ Author :braveyly
//
//


#if !defined(_DOCUMENT_H)
#define _DOCUMENT_H

#include "Receiver.h"

class Document : public Receiver{
public:
	void copy_action();
	void paste_copy();
	void open_action();
	void close_action();
};

#endif  //_DOCUMENT_H
