//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Design Mode Command
//  @ File Name : Invoker.cpp
//  @ Date : 2012-3-16
//  @ Author :braveyly
//
//


#include "Invoker.h"

Invoker::Invoker(Command* cmd):_cmd(cmd) {

}

void Invoker::DoInvoke() {
	_cmd->execute();

}

