//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Design Mode Command
//  @ File Name : MenuItem.h
//  @ Date : 2012-3-16
//  @ Author :braveyly
//
//


#if !defined(_MENUITEM_H)
#define _MENUITEM_H

#include "Invoker.h"

class MenuItem : public Invoker {
public:
	MenuItem(Command*);
	void ClickMenuItem();
};

#endif  //_MENUITEM_H
