//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Design Mode Command
//  @ File Name : PasteCommand.cpp
//  @ Date : 2012-3-16
//  @ Author :braveyly
//
//


#include "PasteCommand.h"

PasteCommand::PasteCommand(Receiver* rec):Command(rec) {

}

void PasteCommand::execute()
{
	get_receiver()->paste_action();
}