//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Design Mode Command
//  @ File Name : Picture.h
//  @ Date : 2012-3-16
//  @ Author :braveyly
//
//


#if !defined(_PICTURE_H)
#define _PICTURE_H

#include "Receiver.h"

class Picture : public Receiver {
public:
	void copy_action();
	void paste_action();
	void open_action();
	void close_action();
};

#endif  //_PICTURE_H
