//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Design Mode Command
//  @ File Name : Picture.cpp
//  @ Date : 2012-3-16
//  @ Author :braveyly
//
//


#include "Picture.h"

void Picture::copy_action() {
	cout<<"copy action of picture"<<endl;
}

void Picture::paste_action() {
	cout<<"paste action of picture"<<endl;
}

void Picture::open_action() {
	cout<<"open action of picture"<<endl;
}

void Picture::close_action() {
	cout<<"close action of picture"<<endl;
}

