//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Design Mode Command
//  @ File Name : Receiver.h
//  @ Date : 2012-3-16
//  @ Author :braveyly
//
//


#if !defined(_RECEIVER_H)
#define _RECEIVER_H
#include <iostream>
#include <string>
using namespace::std;

class Receiver {
public:
	virtual void copy_action();
	virtual void paste_action();
	virtual void open_action();
	virtual void close_action();
};

#endif  //_RECEIVER_H
