//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Design Mode Command
//  @ File Name : Receiver.cpp
//  @ Date : 2012-3-16
//  @ Author :braveyly
//
//


#include "Receiver.h"

void Receiver::copy_action() {

}

void Receiver::paste_action() {

}

void Receiver::open_action() {

}

void Receiver::close_action() {

}

