//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Design Mode Command
//  @ File Name : ToolBar.h
//  @ Date : 2012-3-16
//  @ Author :braveyly
//
//


#if !defined(_TOOLBAR_H)
#define _TOOLBAR_H

#include "Invoker.h"

class ToolBar : public Invoker {
public:
	ToolBar(Command*);
	void ClickToolBar();
};

#endif  //_TOOLBAR_H
